// Some player spawn points around the 3 main cities of San Andreas.
// Thanks to krisk, Popz and Woet.

// Police dept spawns LS/SF/LV.
new Float:gPoliceSpawns[3][4] = {
{2495.0720,-1687.5278,13.5150,359.6696} // Outside CJ's house - lots of cars nearby
};

// Medical dept spawns LS/SF/LV.
new Float:gMedicalSpawns[3][4] = {
{2495.0720,-1687.5278,13.5150,359.6696} // Outside CJ's house - lots of cars nearby
};

// Army spawns LS/SF/LV.
new Float:gArmySpawns[3][4] = {
{2495.0720,-1687.5278,13.5150,359.6696} // Outside CJ's house - lots of cars nearby
};

new Float:gRandomSpawns_LosSantos[][4] = {
{2495.0720,-1687.5278,13.5150,359.6696} // Outside CJ's house - lots of cars nearby
}; 

new Float:gRandomSpawns_LasVenturas[][4] = {
{2495.0720,-1687.5278,13.5150,359.6696} // Outside CJ's house - lots of cars nearby
};

new Float:gRandomSpawns_SanFierro[][4] = {
{2495.0720,-1687.5278,13.5150,359.6696} // Outside CJ's house - lots of cars nearby
};